name: Build and Push To Prod

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Publish Projects
        run: |
          project="./Telegram-bot-openai.csproj"
          runtimes=("linux-x64")
          for runtime in "${runtimes[@]}"; do
            dotnet publish $project /p:DebugType=None /p:DebugSymbols=false -c Release -r $runtime -o "./ProductionBuild/$runtime" --self-contained false
          done
        shell: bash

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./ProductionBuild/linux-x64/*
          git commit -m "Automated build commit" --allow-empty
          git push origin HEAD:${{ github.ref_name }}
        shell: bash

      - name: Transfer Build to Server
        run: |
          scp -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no -r ./ProductionBuild/linux-x64/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:/opt/telegram-bot-openai/
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_SERVER: ${{ secrets.SSH_SERVER }}

      - name: Restart Telegram Bot Service
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} 'sudo systemctl restart telegram-bot-openai.service'
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_SERVER: ${{ secrets.SSH_SERVER }}